name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled, review_requested]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/Lambda-School-Labs/Labs26-Apollo-iOS-TeamA/projects/1'
        
    - name: Move to needs review
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'review_requested'
      with:
        project: 'https://github.com/Lambda-School-Labs/Labs26-Apollo-iOS-TeamA/projects/1'
        column_name: 'Needs review'
